name: spacetimeformer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cython>=0.22
  - cmdstanpy=0.9.68
  - pystan=2.19.1.1
  - numpy>=1.15.4
  - pandas>=1.0.4
  - matplotlib>=2.0.0
  - convertdate>=2.1.2
  - python-dateutil>=2.8.0
  - tqdm>=4.36.1
  - netCDF4
  - scikit-learn
  - omegaconf
  - seaborn
  - chardet
  - opt_einsum
  - pip   # ensures pip is installed in the environment
  - pip:
      - performer-pytorch
      - nystrom-attention
      - pytorch-lightning==1.6.0
      - opencv-python
      - wandb
      - einops
      - torchmetrics==0.5.1
